### ISSUE TITLE
GUI: Web links unavailable on small screens

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2756]
On a screen with low resolution, when the GUI is opened, the Web Links perspective is unavailable. It has been pushed off the bottom of the window and there is no mechanism to scroll.

This is will become more urgent if we activate other perspectives (e.g. Nicos) by default as it will push the synoptic perspective off the screen too.

**Comment by DominicOram** [comment]
@Tom-Willemsen Is this fixed with your new web links implementation?

**Comment by DominicOram** [comment]
Check to see if this is an issue in E4

**Comment by Tom-Willemsen** [comment]
Still an issue in E3 as this refers to the perspective switcher icon as opposed to the perspective itself.

Not an issue in E4.

**Comment by KathrynBaker** [comment]
As we have now moved to E4 I think this is no longer applicable
