### ISSUE TITLE
ICAT: files not appearing in catalogue

### ISSUE THREAD

**Issue by davidkeymer** [ISISComputingGroup/IBEX#4505]
First noticed on ARGUS, but affected all instruments.  Appeared to have stopped at some point over the weekend of 6/7th.

Fault traced to the archive "crawler" process on the ICAT machine (managed by SCD, but located in an ISIS server room) that ingests files in the ISIS archive into the catalogue.  Possibly caused by changes to the access shares for one instrument on the day before.

Remedied by SCD contact restarting the crawler process to enable the catalogue to catch up with the backlog of new data files.

User who reported this suggested adding an alert for this service.  Could be either local NAGIOS or SCD alert system, or both.

**Comment by davidkeymer** [comment]
Sounds a very similar problem and solution as detailed in #4109.

**Comment by DominicOram** [comment]
There's no mention of TOPCAT on the developers wiki. I personally only know a little bit about it and so would have struggled to do this support ticket. Can you add a page to the wiki with enough info so that others could diagnose similar problems in the future?

Has the NAGIOS check now been added? Can we do that as part of this ticket or make a new ticket to do it?

**Comment by FreddieAkeroyd** [comment]
There are nagios checks that the TOPCAT people asked us to add for their benefit and they email them directly, however these checks only flagged issues when the service was restarted monday. I'm not sure if the checks are emailing the current people involved in TOPCAT, but as the checks did not spot the problem we need them to send us another system or service to check

**Comment by FreddieAkeroyd** [comment]
There is an ICAT entry in http://sparrowhawk.nd.rl.ac.uk/footprints/ that can be used to report issues, i will add TOPCAT to the description here too

**Comment by FreddieAkeroyd** [comment]
Or email isisdata@stfc.ac.uk

**Comment by davidkeymer** [comment]
The issue that this ticket refers to was resolved by the responsible member of SCD restarting the ingestion process.

To monitor this process, a separate ticket #4520 has been created.

**Comment by DominicOram** [comment]
I still can't find any documentation on the wiki about this. It doesn't need much just:
* What is TOPCAT?
* How does it relate to ICAT?
* How do I know if it's gone wrong?
* Who do I contact in this case (e.g. what's discussed in this ticket)

**Comment by davidkeymer** [comment]
Page created under [Trouble Shooting](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/trouble-shooting-pages)

**Comment by DominicOram** [comment]
Great, thanks David!
