### ISSUE TITLE
IOC tests: fix hanging behaviour when running all tests

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/IBEX#6256]
The linmot IOC tests were causing hanging on jenkins when running all of the tests, at least on RENO, so these were disabled in https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/418
Some investigation was done on this but was taking too long so this ticket was created. The tests were trying to start up the lewis emulator for the linmot (which is also used in the gem_jaws ioc tests) but it was hanging on this step. 
These should be fixed and re-enabled on jenkins. 

### Acceptance criteria 
- Tests are fixed 
- Tests are re-enabled on jenkins
- Tests do not cause hanging

**Comment by rerpha** [comment]
Note: last commit with the tests on master was [04a89a465a450c6a5ce9f3a23297f73e42231104](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/tree/04a89a465a450c6a5ce9f3a23297f73e42231104)

**Comment by rerpha** [comment]
Linmot tests have now been added back in and have suddenly started running + passing again. Not sure why they are now fixed but all the extra logging is now no longer needed - review https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/427 as part of this ticket.

**Comment by ThomasLohnert** [comment]
https://github.com/ISISComputingGroup/IBEX/pull/6275

**Comment by KathrynBaker** [comment]
When reviewing it was realised that they are still not quite working, so unfortunately have gone back for rework.

**Comment by rerpha** [comment]
It's really weird - it hung on build 7490 but has now passed on build 7491... I will keep trying to reproduce it on my local machine overnight.

**Comment by rerpha** [comment]
Not entirely sure what to do from here - the tests haven't hung for the last few builds (or at least the last few builds that ran the tests), so seems to be intermittent.

**Comment by John-Holt-Tessella** [comment]
@rerpha Put some extra logging in, print statements at strategic places to see if you can catch where it is hanging. Then call it a day :-)

**Comment by rerpha** [comment]
Have re-enabled the logging, going to run the tests tonight and investigate logs next time it hangs.

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/438 - doing this temporarily on the build server to see what happens. If this fixes it we should write a more permanent solution and revert the change in that PR.

**Comment by rerpha** [comment]
Having looked at build no. 7539 which ran the linmots first, i suspect the linkam is the culprit here!

**Comment by DominicOram** [comment]
The same error is now happening with the `TPG26X` I think this is due to errors in the `TEKAFG3XXX` beforehand.

**Comment by rerpha** [comment]
> The same error is now happening with the `TPG26X` I think this is due to errors in the `TEKAFG3XXX` beforehand.

https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/112

**Comment by rerpha** [comment]
https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/458 should fix all of the IOC tests that have broken because of the change of how we use the backdoor, remaining to do on this ticket is move the Lewis installation into genie python itself.

**Comment by rerpha** [comment]
PRs for the lewis reinstallation: 

genie python: https://github.com/ISISComputingGroup/genie_python/pull/328
ioc test framework: https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/459

**Comment by rerpha** [comment]
To recap, the hanging was not due to the linmot, linkam or TPG tests, and rather the way we were using the lewis backdoor. We instead now use the lewis-control executable from a separate process (like before) though we have to re-install lewis on the client machine after it has been copied from the build server. 

To review this ticket: 
- check the PRs above re-install lewis on the client machine after copying it from the build server when updating genie python 
- merge them 
- wait for an ioc tests run to complete on jenkins 
- confirm that the ioc tests are no longer hanging (failures are fine, there are some genuine failures that still need to be fixed, but I or anyone else responsible for them will be fixing these in flash reviews)

**Comment by DominicOram** [comment]
I'm not going to review this as I did a lot of the work with you but can you also remove all the additional logging we added to see what was going on? e.g. the control port etc.

**Comment by rerpha** [comment]
> I'm not going to review this as I did a lot of the work with you but can you also remove all the additional logging we added to see what was going on? e.g. the control port etc.

Done, pushed to branch listed in the PR above.

**Comment by rerpha** [comment]
I'll just take rework off so we can get this through, easy one to review as it just requires checking that the builds are not hanging anymore (hint: they aren't) and reviewing the two above PRs for re-installing lewis in genie python rather than `run_all_tests.bat`
